"$schema" = 'https://starship.rs/config-schema.json'

format = """
\
[$character](bg:#de0055)\
([$jobs](bg:#de0055))\
($sudo)\
\
$username\
$directory\
[î‚°](fg:#8d02b8 bg:#de0055)\
\
\
\
(\
[î‚°](fg:#de0055 bg:#0da68a)\
$git_status\
$git_branch\
[î‚°](bg:#de0055 fg:#0da68a)\
)\
\
\
\
(\
$c\
$cobol\
$crystal\
$dart\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$haskell\
$java\
$julia\
$kotlin\
$lua\
$nodejs\
$nim\
$ocaml\
$perl\
$php\
$python\
$red\
$rlang\
$ruby\
$rust\
$scala\
$swift\
$vlang\
$zig\
)\
\
\
[î‚°](fg:#de0055)\
\
"""

#

# Disable the blank line at the start of the prompt
add_newline = true


[sudo]
symbol = "â­"
style = "bg:#de0055"
format = "[$symbol]($style)"
disabled = false

[character]
success_symbol = " "
error_symbol = "[ âœ—](bold fg:black bg:#fa1419)[î‚°](fg:#fa1419 bg:#de0055)"
format = "$symbol"

[username]
show_always = false
style_user = "#8d02b8"
style_root = "#e35102 bold"
format = '$sudo[î‚°](fg:#de0055 bg:$style)[$user ](bg:$style)[î‚°](fg:$style bg:#de0055)'

[directory]
style = "bg:#8d02b8"
format = "[î‚°](fg:#de0055 $style)[$path ]($style)"
truncation_length = 2
truncation_symbol = "â€¦/"

[directory.substitutions]
"Code" = "ğŸ’»"
"Documents" = "ğŸ“‚"
"Downloads" = "ğŸ“¥"
"Music" = "ğŸ§"
"Pictures" = "ğŸ“·"
"Public" = "ğŸ‘¤"
"Templates" = "ğŸ“"
"Videos" = "ğŸ¬"
"~" = "ğŸ "

[jobs]
symbol = "ğŸ“‹"
number_threshold = 2
symbol_threshold = 1
style = "bg:#666666"
format = "[î‚°](fg:#de0055 bg:#666666)[$symbol$number]($style)[î‚°](fg:#666666 bg:#de0055)"


[git_branch]
symbol = "ï˜"
style = "bg:#0da68a"
format = '[$symbol](fg:#2c5221 $style)[$branch]($style)'
disabled = true

[git_status]
style = "bg:#0da68a"
conflicted = "ğŸ˜“ "
modified = "[î•° ](fg:#2c5221 bg:#0da68a)"
stashed = "[î¯› $count ](fg:#2c5221 bg:#0da68a)"
format = '[$all_status$ahead_behind]($style)'
disabled = true

[c]
symbol = " î˜ "
style = "bold fg:#3486eb bg:#222222"
format = '[î‚°](fg:#de0055 bg:#222222)[$symbol]($style)[î‚°](fg:#222222 bg:#de0055)'

[cobol]
symbol = " âš™ï¸ "
style = "#168fc7"
format = '[î‚°](fg:#de0055 bg:#222222)[$symbol](fg:$style bg:#222222)[î‚°](fg:#222222 bg:#de0055)'

[crystal]
symbol = " î˜¯ "
style = "bold #cccccc"
format = '[î‚°](fg:#de0055 bg:#222222)[$symbol](fg:$style bg:#222222)[î‚°](fg:#222222 bg:#de0055)'


[dart]
symbol = " î˜ "
style = "bold #41c4ff"
format = '[î‚°](fg:#de0055 bg:#222222)[$symbol](fg:$style bg:#222222)[î‚°](fg:#222222 bg:#de0055)'

[dotnet]
symbol = ".net" # îœ®
style = "bold fg:#2fb000 bg:#222222"
format = "[î‚°](fg:#de0055 bg:#222222)[$symbol($version )(ğŸ¯ $tfm )]($style)[î‚°](fg:#222222 bg:#de0055)"
heuristic = true

[elixir]
symbol = " î‰µ "
style = "bold #7921d1"
format = '[î‚°](fg:#de0055 bg:#222222)[$symbol](fg:$style bg:#222222)[î‚°](fg:#222222 bg:#de0055)'

[elm]
symbol = "elm" # î˜¬
style = "bold #1293d8"
format = '[î‚°](fg:#de0055 bg:#222222)[$symbol](fg:$style bg:#222222)[î‚°](fg:#222222 bg:#de0055)'

[erlang]
symbol = " î± "
style = "#de0055"
format = '[î‚°](fg:#de0055 bg:#222222)[$symbol](fg:$style bg:#222222)[î‚°](fg:#222222 bg:#de0055)'

[golang]
symbol = " î˜§ "
style = "bold #8cd2e2"
format = '[î‚°](fg:#de0055 bg:#222222)[$symbol](fg:$style bg:#222222)[î‚°](fg:#222222 bg:#de0055)'

[haskell]
symbol = " î· " # Î»
style = "bold #a402b3"
format = '[î‚°](fg:#de0055 bg:#222222)[$symbol](fg:$style bg:#222222)[î‚°](fg:#222222 bg:#de0055)'

[java]
symbol = " î‘ "
style = "bold #b38346"
format = '[î‚°](fg:#de0055 bg:#222222)[$symbol](fg:$style bg:#222222)[î‚°](fg:#222222 bg:#de0055)'

[julia]
symbol = " î˜¤ "
style = "bold #4063d8"
format = '[î‚°](fg:#de0055 bg:#222222)[$symbol](fg:$style bg:#222222)[î‚°](fg:#222222 bg:#de0055)'

[kotlin]
symbol = " ğŸ…º "
style = "bold blue"
format = '[î‚°](fg:#de0055 bg:#222222)[$symbol](fg:$style bg:#222222)[î‚°](fg:#222222 bg:#de0055)'

[lua]
symbol = " î˜  "
style = "bold #354dfc"
format = '[î‚°](fg:#de0055 bg:#222222)[$symbol](fg:$style bg:#222222)[î‚°](fg:#222222 bg:#de0055)'

[nodejs]
symbol = " î "
style = "bold #2ca600"
format = '[î‚°](fg:#de0055 bg:#222222)[$symbol](fg:$style bg:#222222)[î‚°](fg:#222222 bg:#de0055)'

[nim]
symbol = " ïš¤ "
style = "#f0bc05"
format = '[î‚°](fg:#de0055 bg:#222222)[$symbol](fg:$style bg:#222222)[î‚°](fg:#222222 bg:#de0055)'

[ocaml]
symbol = " ğŸ« "
style = "#2ca600"
format = '[î‚°](fg:#de0055 bg:#222222)[$symbol](fg:$style bg:#222222)[î‚°](fg:#222222 bg:#de0055)'

[perl]
symbol = " ğŸª "
style = "#7705f0"
format = '[î‚°](fg:#de0055 bg:#222222)[$symbol](fg:$style bg:#222222)[î‚°](fg:#222222 bg:#de0055)'


[php]
symbol = " ğŸ˜ "
style = "#7705f0"
format = '[î‚°](fg:#de0055 bg:#222222)[$symbol](fg:$style bg:#222222)[î‚°](fg:#222222 bg:#de0055)'

[python]
symbol = " î˜† "
style = "bold #ffd241"
format = '[î‚°](fg:#de0055 bg:#222222)[$symbol](fg:$style bg:#222222)[î‚°](fg:#222222 bg:#de0055)'

[red]
symbol = " ğŸ”º "
style = "bold #a51601"
format = '[î‚°](fg:#de0055 bg:#222222)[$symbol](fg:$style bg:#222222)[î‚°](fg:#222222 bg:#de0055)'

[rlang]
symbol = " R "
style = "bold #bf1a02"
format = '[î‚°](fg:#de0055 bg:#222222)[$symbol](fg:$style bg:#222222)[î‚°](fg:#222222 bg:#de0055)'


[ruby]
symbol = " îœ¹ "
style = "bold #a51601"
format = '[î‚°](fg:#de0055 bg:#222222)[$symbol](fg:$style bg:#222222)[î‚°](fg:#222222 bg:#de0055)'

[rust]
symbol = " ğŸ¦€ "
style = "#823026"
format = '[î‚°](fg:#de0055 bg:#222222)[$symbol](fg:$style bg:#222222)[î‚°](fg:#222222 bg:#de0055)'
#format = '[î‚°](fg:#de0055 bg:$style)[$symbol](bg:$style)[î‚°](fg:$style bg:#de0055)'

[scala]
symbol = " îœ· "
style = "#e52e2a"
format = '[î‚°](fg:#de0055 bg:#222222)[$symbol](fg:$style bg:#222222)[î‚°](fg:#222222 bg:#de0055)'

[swift]
symbol = " î• "
style = "#f05138"
format = '[î‚°](fg:#de0055 bg:#222222)[$symbol](fg:$style bg:#222222)[î‚°](fg:#222222 bg:#de0055)'

[vlang]
symbol = " v "
style = "#3075d1"
format = '[î‚°](fg:#de0055 bg:#222222)[$symbol](fg:$style bg:#222222)[î‚°](fg:#222222 bg:#de0055)'

[zig]
symbol = " â†¯ "
style = "#f7a41d"
format = '[î‚°](fg:#de0055 bg:#222222)[$symbol](fg:$style bg:#222222)[î‚°](fg:#222222 bg:#de0055)'

[time]
disabled = true
time_format = "%R"             # Hour:Minute Format
style = "bg:#33658A"
format = '[ â™¥ $time ]($style)'
